services:
  postgres:
    image: postgres:16
    container_name: todo-list
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
